application: cinsoftphp
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: index.php
  
- url: /css
  static_dir: css
  mime_type: text/css
  
- url: /js
  static_dir: js
  mime_type: application/javascript
  
- url: /images
  static_dir: images
  mime_type: image/jpg
